# NumPy for machine learning
## Numpy
- It is the fundamental package for scientific computing with python
- A powerful n-dimentional array object
- Sophestiated (broadcasting) functions
- Tolls for integrating C/C++ and fortran code
- USeful linear algebra. fourire transform and rando number capabilities

##  Importing Convensitions

In [1]:
import numpy as np

## Creating arrays
### 1-D Array

In [4]:
a = np.array([0,1,2,3])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.ndim

1

In [7]:
a.shape

(4,)

### 2-D 3-D


In [23]:
b = np.array([
    [1,2,3],
    [7,8,9]
])

In [24]:
b

array([[1, 2, 3],
       [7, 8, 9]])

In [25]:
b.ndim

2

In [26]:
b.shape

(2, 3)

###  Functions for creating array
- ### arange


In [21]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [22]:
print(np.arange(1,9,2))

[1 3 5 7]


### Number by Points

In [33]:
print(np.linspace(0,1,10))

[ 0.          0.11111111  0.22222222  0.33333333  0.44444444  0.55555556
  0.66666667  0.77777778  0.88888889  1.        ]


###  Common Arrays

In [34]:
a = np.ones((3,3))

In [35]:
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [36]:
b = np.zeros((2,2))

In [37]:
b

array([[ 0.,  0.],
       [ 0.,  0.]])

In [38]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [40]:
a=np.diag(np.arange(5))

In [42]:
a[1,1]

1

In [43]:
a[1][1]

1

In [44]:
a[2,1]=10

In [45]:
a

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0],
       [ 0, 10,  2,  0,  0],
       [ 0,  0,  0,  3,  0],
       [ 0,  0,  0,  0,  4]])

In [46]:
a[1]

array([0, 1, 0, 0, 0])

In [49]:
a=np.arange(10)

In [54]:
a[2:9:3]

array([2, 5, 8])

In [57]:
a=np.ones((4,4), dtype=int)

In [59]:
a[3,1], a[2,3]=6,2

In [60]:
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 6, 1, 1]])

In [96]:
a=np.zeros((5,6),dtype=int)

In [97]:
b=np.diag(np.arange(6)+1)

In [99]:
c=a[1:]

In [100]:
c

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

ValueError: operands could not be broadcast together with shapes (4,6) (6,6) 